name: Get Sentiment and update GitHub page

on:
  schedule:
    - cron: "30 11 * * *" #runs at 11:30 utc (17:00 ist) everyday
    
jobs:
  refresh_page:
    runs-on: ubuntu-latest    
    steps:
      - name: Access the repo
        uses: actions/checkout@v2 
    
      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10' 
      
      - name: Install necessary libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Execute fetch-data python file
      - run: python fetch-data.py

      - name: Execute python script to update sentiment page
        run: python dashboard-generation.py

        
      - name: Clone repo from your github.io page and commit newly generated sentiment html file
        run: | #change all the "damianboh"s below to your username
          git clone https://github.com/OsamaMustafa/OsamaMustafa.github.io.git/ 
          cp NIFTY_500_live_sentiment.html OsamaMustafa.github.io/NIFTY_500_live_sentiment.html 
          cd OsamaMustafa.github.io 
          git add NIFTY_500_live_sentiment.html
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'refresh NIFTY_500_live_sentiment page'        
        
      - name: Push updated html to github.io page
        uses: ad-m/github-push-action@master
        with: #change all the "damianboh"s below to your username
          github_token: ${{ secrets.TOKEN }}          
          repository: "OsamaMustafa/OsamaMustafa.github.io"
          branch: "main"          
          directory: ./OsamaMustafa.github.io
          
        
